name: Build

on:
  pull_request_target:
    branches:
      deploy

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      - name: Yarn install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
